package solap;

import javax.xml.ws.WebServiceRef;

import org.w3c.dom.Document;

import org.w3c.dom.Element;

import solap.SOLAPServer;
import solap.SOLAPServerService;

import solap.utils.XMLUtils;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

public class SOLAPServerPortClient
{
  @WebServiceRef
  private static SOLAPServerService sOLAPServerService;
  private XMLUtils xmlUtils = new XMLUtils();


    public String executeRequest(String requestText) {
        sOLAPServerService = new SOLAPServerService();
        SOLAPServer sOLAPServer = sOLAPServerService.getSOLAPServerPort();
        
        /*String xml = sOLAPServer.solapQuery(requestText);
        Document doc = xmlUtils.XmlToDoc(xml);
        Element elem = (Element)doc.getDocumentElement().getElementsByTagName("ROW").item(3);
        System.out.println(elem.getAttribute("num"));*/
      
        return sOLAPServer.solapQuery(requestText);
    }
}
