package solap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 081105.0700.56405)

@WebService(wsdlLocation="http://localhost:7101/SOLAP-Server-context-root/SOLAPServerPort?wsdl",
  targetNamespace="http://solap/", name="SOLAPServer")
@XmlSeeAlso(
  { types.ObjectFactory.class })
public interface SOLAPServer
{
  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="solapQueryResponse", targetNamespace="http://solap/",
    className="types.SolapQueryResponse")
  @RequestWrapper(localName="solapQuery", targetNamespace="http://solap/",
    className="types.SolapQuery")
  @WebResult(targetNamespace="")
  public String solapQuery(@WebParam(targetNamespace="", name="arg0")
    String arg0);
}
